"""initial migration

Revision ID: baaff1002a3b
Revises: 
Create Date: 2026-02-14 15:33:21.594613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baaff1002a3b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_feeds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('product_name', sa.String(length=512), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('country_code', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('index_pricing_feeds_store_sku_date', 'pricing_feeds', ['store_id', 'sku', 'date'], unique=False)
    op.create_index(op.f('ix_pricing_feeds_country_code'), 'pricing_feeds', ['country_code'], unique=False)
    op.create_index(op.f('ix_pricing_feeds_date'), 'pricing_feeds', ['date'], unique=False)
    op.create_index(op.f('ix_pricing_feeds_sku'), 'pricing_feeds', ['sku'], unique=False)
    op.create_index(op.f('ix_pricing_feeds_store_id'), 'pricing_feeds', ['store_id'], unique=False)
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uploads')
    op.drop_index(op.f('ix_pricing_feeds_store_id'), table_name='pricing_feeds')
    op.drop_index(op.f('ix_pricing_feeds_sku'), table_name='pricing_feeds')
    op.drop_index(op.f('ix_pricing_feeds_date'), table_name='pricing_feeds')
    op.drop_index(op.f('ix_pricing_feeds_country_code'), table_name='pricing_feeds')
    op.drop_index('index_pricing_feeds_store_sku_date', table_name='pricing_feeds')
    op.drop_table('pricing_feeds')
    # ### end Alembic commands ###
